/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

function Model(props) {
  const { nodes, materials } = useGLTF("./scene.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface466.geometry}
        material={materials.NewMat01}
        position={[0.03, 3.49, 0]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface466001.geometry}
        material={materials.Wick_MAT}
        position={[0.03, 2.3, 0]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface470.geometry}
        material={materials.candle}
        position={[0.02, 3.23, 0]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface452.geometry}
        material={materials.iron}
        position={[-0.26, 4.15, -0.02]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface453.geometry}
        material={materials.iron}
        position={[-1.35, 3.1, -0.02]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface454.geometry}
        material={materials.iron}
        position={[-1.34, 2.99, -0.02]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface455.geometry}
        material={materials.iron}
        position={[0, 4.31, -0.01]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface456.geometry}
        material={materials.iron}
        position={[0, 4.59, -0.02]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface457.geometry}
        material={materials.iron}
        position={[0.01, 6.81, -0.02]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface458.geometry}
        material={materials.iron}
        position={[0, 6.55, -0.03]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface459.geometry}
        material={materials.iron}
        position={[0.36, 3.39, -0.01]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface461.geometry}
        material={materials.decor_iron}
        position={[0.03, 2.74, -0.02]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface460.geometry}
        material={materials.wood}
        position={[0.03, 2.77, -0.02]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface451.geometry}
        material={materials.chains}
        position={[0.01, 4.07, -0.02]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fakel1.geometry}
        material={materials.fakel}
        position={[0.03, 3.03, -0.01]}
        scale={0.02}
      />
    </group>
  );
}

useGLTF.preload("./scene.glb");

export default Model;
